//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Especialidad = new HashSet<Especialidad>();
        }
    
        public int DoctorID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string CI { get; set; }
        public byte[] Foto { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<decimal> ValorConsulta { get; set; }
        public Nullable<decimal> SueldoMinimo { get; set; }
        public bool IsDirector { get; set; }
        public int UsuarioID { get; set; }
        public bool Active { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Especialidad> Especialidad { get; set; }
    }
}
